### ISSUE TITLE
Problem with reading MPU6050

### ISSUE THREAD

**Issue by moelski** [ghmartin77/B-ROBOT_EVO2_ESP32#1]
Hi !
First of all thx for this code. We try to build the B-Robot and come along with a problem reading the Gyro. 

```
// MPU6050_read n bytes
int MPU6050_read(int start, uint8_t *buffer, int size)
{
  int i, n, error;

  Wire.beginTransmission(MPU6050_I2C_ADDRESS);
  n = Wire.write(start);
  if (n != 1)
    return (-10);

  n = Wire.endTransmission(false);    // hold the I2C-bus
    if (n != 0)
       return (n);
```

Wire.endTransmission(false) returns no longer a value like 0. It returns a value of 7 because the data transfered to the I2C device is queued. And the result is a not working MPU6050.
Even rewriting the part to check for n != 7 didn´t work correctly. 

So did you ever compile your sketch against the latest git master of the ESP32 Arduino Core? 

Would be great if you can make a test and come back maybe with a fix. 

regards
  Dominik

**Comment by moelski** [comment]
Well just tested it by myself and this no longer seems an issue. 
We only need some changes in MPU6050_read
```
  n = Wire.endTransmission(false);    // hold the I2C-bus
  //if (n != 0)
  //  return (n);

  // Third parameter is true: relase I2C-bus after data is read.
  Wire.requestFrom((uint8_t) MPU6050_I2C_ADDRESS, (int) size, true);
```
That way it seems to work ...

**Comment by ghmartin77** [comment]
Seems to be related to what is documented in README.md:
Important note: At the time of this writing (January 2018) the recent version of arduino-esp32 contains changes that break the I2C communication with the IMU a few seconds after startup. This version is known to work reliably for the purpose of the robot: https://github.com/espressif/arduino-esp32/tree/32c028a27e6b3c3c3df769bb42f0d87917e0309c

For more details on the I2C problem mentioned, please refer to these issues (haven't tried the forks mentioned there):

    https://github.com/espressif/arduino-esp32/issues/834
    https://github.com/espressif/arduino-esp32/issues/839

Please also have a look here. Some people managed to make I2C work in later versions:
http://forums.jjrobots.com/thread-1399-page-4.html

**Comment by ghmartin77** [comment]
Closed since Arduino-ESP32's **I2C implementation is working again at least with 1.0.2**.
